### ISSUE TITLE
Freeze on Connect in 1.4.0-beta.6 (regression, bisected to afv-native update)

### ISSUE THREAD

**Issue by uetcis** [pierr3/TrackAudio#353]
## Summary

TrackAudio freezes on clicking **Connect**, on every attempt. This is a regression introduced between `1.4.0-beta.4` and `1.4.0-beta.6` — `1.3.3` and `1.4.0-beta.4` both connect fine; `1.4.0-beta.6` reliably fails.

I've seen two manifestations of this on the same bisected source build (`afv-native` @ `649d7f1`), across repeated connect attempts, which I believe are the same underlying issue surfacing differently depending on timing:
- **Most commonly** (and matching my original experience on the installed `1.4.0-beta.6` package): a silent, indefinite freeze — no error message, no log output, app has to be force-quit. I added a temporary trace at the point where the backend sends any error event to the renderer (`AfvEventTypes.Error`) and confirmed **no error event fires at all** in this case, in either the JS-side log or the native (`plog`) log file — the relevant thread is genuinely stuck, not just slow.
- **Occasionally**, on one attempt: the freeze resolved after several seconds into a gui error prompt on AFV connection error (exact msg forgotten)

Given the underlying code (see bisect below) is in a threading/polling rewrite, I suspect this is a race: usually the stalled request never completes and never times out (indefinite hang, no error), and occasionally something does eventually time out and the error event fires instead.

This looks related to #332, but is a distinct symptom: #332 reports an intermittent crash-to-desktop on Windows, while this is a **100% reproducible freeze** (not a crash) on Linux/Wayland.

## Environment

- OS: Arch Linux, Wayland session
- Affected: `1.4.0-beta.6` (and likely beta.5)
- Not affected: `1.3.3`, `1.4.0-beta.1`, `1.4.0-beta.4`

## Steps to reproduce

1. Launch TrackAudio `1.4.0-beta.6`.
2. Connect to the network (e.g. via EuroScope).
3. Click the **Connect** (audio) button in TrackAudio.
4. UI freezes. Usually this is an indefinite silent freeze (no error, no log output, requires force-quit). Occasionally it resolves after several seconds into a GUI error prompt about the AFV connection instead (exact wording not captured).

Internet connectivity is fine; the freeze itself reproduces every time (100% of attempts), even though whether it silently hangs vs. eventually errors varies between attempts.

## Bisect results

I bisected against source builds (backend + frontend, Linux/npm) to narrow this down:

**TrackAudio-level bisect** (`1.3.3` good → `1.4.0-beta.6`/`main` bad):

| Commit | Result |
|---|---|
| `1.3.3` | GOOD |
| `1.4.0-beta.1` (`c1693d4`) | GOOD (built from source; connects fine) |
| `bd81ad8` | GOOD |
| `72c8685` "Bump to 1.4.0-beta.4, update afv-native with threading fixes" | GOOD |
| `413ab59` "waylandbodge" (docs-only, PR #333) | GOOD |
| `a6f04c4` "Update afv native, fixes" | **BAD** (first bad commit) |

`a6f04c4`'s only functional changes are the `afv-native` submodule bump (`c2154af` → `fb107d7`) and a 7-line safety fix in `backend/src/RemoteData.cpp`. I isolated these: rebuilding `a6f04c4`'s tree with `afv-native` pinned back to `c2154af` connects **fine**, confirming the regression is entirely inside the `afv-native` bump, not `RemoteData.cpp`.

**afv-native sub-bisect** (`c2154af` good → `fb107d7` bad), same TrackAudio tree throughout:

```
c2154af  Fix threading bugs causing freezes and crashes     GOOD
13d17b8  Remove redundant code in device stopped notification GOOD
1040b78  Merge pull request #17 (miniaudio-patch)            GOOD
96a36d3  Bump miniaudio                                       \\_ untested (build broken,
e1f7651  Merge branch 'develop-trackaudio'                    /   see below)
3c4dc3e  Update miniaudio.c                                  \\_ untested (build broken)
dcd0210  Race condition fixes                                 /
649d7f1  Fix miniaudio include path                          BAD (reproduces the error)
fb107d7  fix internal plumbing using deprecated methods      BAD (confirmed, reliable)
```

- `96a36d3`, `e1f7651`, `3c4dc3e`, and `dcd0210` fail to compile in isolation (`miniaudio.c:2:10: fatal error: audio/miniaudio.h: No such file or directory`), which is only fixed by `649d7f1`. So the earliest commit in this range that will actually build is `649d7f1`, and it already reproduces the freeze reliably (usually silent, occasionally with the error prompt described above).
- `fb107d7`'s diff (`include/afv-native/http/TransferManager.h`, `src/http/Request.cpp`, `src/http/TransferManager.cpp`) extracts `TransferManager::HandleRequest`'s body into a new `submitRequest` method and calls that instead — this is a behavior-preserving refactor (`PollingTransferManager` doesn't override `HandleRequest`), so it can't be the actual root cause; it just inherits the bug from its parent.

**Conclusion:** the regression was introduced by one of the miniaudio-bump / threading commits between `1040b78` (good) and `649d7f1` (bad) — most likely `96a36d3` "Bump miniaudio" or `dcd0210` "Race condition fixes" — landing in `afv-native`'s `develop-trackaudio` branch and pulled into TrackAudio via `a6f04c4`.

## Suspected cause

Most likely candidate for the occasional error prompt is `afv_native::afv::APISessionError::ConnectionError`, raised via `APIServerErrorEvent` in `backend/src/main.cpp` (I didn't capture the exact on-screen wording from that one occurrence, but it lines up with an AFV API connection failure). This fires when an AFV API HTTP request fails. Given the timing (this window is exactly where `afv-native`'s HTTP layer was being reworked — `PollingTransferManager`, curl-multi handling — combined with "Race condition fixes" and a miniaudio bump), I suspect a race between the polling thread and request submission that causes the initial AFV API session request to stall indefinitely — the request is submitted but never actually gets serviced by the poll thread (e.g. never added to the curl multi handle, or a missed wakeup), so it just sits forever with no timeout ever firing. On the rare run where something else does time out first, an error prompt appears instead; otherwise there's no error path at all, which matches what I observed (confirmed via a temporary trace on every backend error-event emission — most hangs produce zero log output on any layer).

## Suggested workaround

Until this is fixed, `1.4.0-beta.4` (`72c8685`) is the last version I could confirm connects reliably and has a public release binary.

## Would like to help

Happy to test candidate fixes against this bisected range if useful — I have a working build setup (Linux/npm, vcpkg cached) that reproduces this reliably.

**Comment by pierr3** [comment]
TrackAudio does not support Wayland, see readme so any issues reproducible solely on Wayland are not going to be supported, you are free to open a PR if you wish to assist.
